version: "3.7"

services:

  database:
    image: mysql:5.7  
    container_name: database 
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: kodal035
      MYSQL_PASSWORD: example12345
    networks:
      - clarusnet

  myapp:
    image: bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet

networks:
  clarusnet:
  


